name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['coqorg/coq:8.12-ocaml-4.07-flambda']
        # the following list must be a singleton (space-separated string)
        src: ['tapfa_coq_1.v tapfa_coq_2.v tapfa_coq_3.v']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          custom_script: |
            startGroup 'Print opam config'
              opam config list; opam repo list; opam list
            endGroup
            startGroup 'Install serapi'
              opam update -y
              opam install -y -v -j 2 "coq-serapi>=8.12.0+0.12.0"
            endGroup
            startGroup 'Install APT/PyPI dependencies'
              sudo apt-get update -y -q
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
                python3-pip
              python3 -m pip install --user --upgrade pygments dominate beautifulsoup4 docutils
            endGroup
            # TODO Later on: cache steps above in a Docker image
            startGroup 'Workaround permissions issue'
              sudo chown -R coq:coq .
              # the container user has UID=GID=1000,
              # while the GHA workdir has (UID=1001, GID=116).
            endGroup
            startGroup 'Create output/'
              mkdir -v output
              rsync -av static/ output/
            endGroup
            startGroup 'Clone Alectryon'
              git clone https://github.com/cpitclaudel/alectryon.git
            endGroup
            startGroup 'Use Alectryon'
              for item in ${{ matrix.src }}; do
                cp -av "src/$item" "output/$item"
                alectryon/alectryon.py --frontend coq+rst "src/$item" \
                  --backend webpage --output-directory output
              done
            endGroup
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
